// =============================================================================
// OPCIONES DE TRANSPORTE - DATOS DE AUTORELLENADO
// =============================================================================
// Este archivo contiene las opciones de transporte para autocompletar
// información en los formularios
// =============================================================================

export const transportOptions = {
  // Tipos de transporte
  transportTypes: [
    { value: 'auto', label: 'Automóvil' },
    { value: 'camioneta', label: 'Camioneta' },
    { value: 'camion', label: 'Camión' },
    { value: 'bus', label: 'Bus' },
    { value: 'micro', label: 'Micro' },
    { value: 'taxi', label: 'Taxi' },
    { value: 'uber', label: 'Uber' },
    { value: 'cabify', label: 'Cabify' },
    { value: 'bicicleta', label: 'Bicicleta' },
    { value: 'moto', label: 'Motocicleta' },
    { value: 'transporte_publico', label: 'Transporte Público' },
    { value: 'caminando', label: 'Caminando' },
    { value: 'caballo', label: 'Caballo' },
    { value: 'helicoptero', label: 'Helicóptero' },
    { value: 'avion', label: 'Avión' },
    { value: 'barco', label: 'Barco' },
    { value: 'lancha', label: 'Lancha' },
    { value: 'ferry', label: 'Ferry' },
    { value: 'tren', label: 'Tren' },
    { value: 'metro', label: 'Metro' }
  ],

  // Marcas de vehículos
  vehicleBrands: [
    'Toyota',
    'Nissan',
    'Honda',
    'Mazda',
    'Subaru',
    'Mitsubishi',
    'Suzuki',
    'Daihatsu',
    'Lexus',
    'Infiniti',
    'Acura',
    'Chevrolet',
    'Ford',
    'Dodge',
    'Chrysler',
    'Jeep',
    'Buick',
    'Cadillac',
    'Lincoln',
    'Pontiac',
    'Volkswagen',
    'Audi',
    'BMW',
    'Mercedes-Benz',
    'Porsche',
    'Volvo',
    'Saab',
    'Opel',
    'Peugeot',
    'Renault',
    'Citroën',
    'Fiat',
    'Alfa Romeo',
    'Lancia',
    'Ferrari',
    'Lamborghini',
    'Maserati',
    'Lotus',
    'Jaguar',
    'Land Rover',
    'Mini',
    'Rolls-Royce',
    'Bentley',
    'Aston Martin',
    'McLaren',
    'Bugatti',
    'Koenigsegg',
    'Pagani',
    'Rimac',
    'Tesla',
    'Rivian',
    'Lucid',
    'Polestar',
    'NIO',
    'XPeng',
    'BYD',
    'Geely',
    'Great Wall',
    'Haval',
    'Chery',
    'JAC',
    'MG',
    'Roewe',
    'Maxus',
    'Dongfeng',
    'FAW',
    'Changan',
    'GAC',
    'BAIC',
    'SAIC',
    'Dongfeng',
    'FAW',
    'Changan',
    'GAC',
    'BAIC',
    'SAIC'
  ]
};

export default transportOptions; 